issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"

linters:
  disable-all: false
  disable:
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint
  enable-all: true
